name: Discord2FA
author: EylexLive
version: 3.2
main: io.github.eylexlive.discord2fa.Main
softdepend: [AuthMe, LoginSecurity]

commands:
  auth:
    aliases: [dcauth]
  discord2fa:
    aliases: [dc2fa, dca]