name: Discord2FA
version: ${project.version}
author: EylexLive
main: io.github.eylexlive.discord2fa.Main
description: ${project.description}
softdepend: [AuthMe, LoginSecurity]

commands:
  auth:
    aliases: [dcauth]
  discord2fa:
    aliases: [dc2fa, dca]