name: Discord2FA
author: EylexLive
version: 2.7
main: io.github.eylexlive.discord2fa.Main
softdepend: [AuthMe, AuthMeReloaded, LoginSecurity]

commands:
  auth:
    aliases: [dcauth]
  discord2fa:
    aliases: [dc2fa, dca]